#SPDX-License-Identifier: MIT-0
# handlers file for react_app
---
- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  # Use "restarted" if you want full restart. reload is gentler.
