---
# Install Node.js 22.x for backend applications

- name: Remove old NodeSource repo if exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/nodesource.list
    state: absent

- name: Ensure that the cache is up-to-date
  ansible.builtin.apt:
    update_cache: yes
  tags: nodejs

- name: Ensure curl and build tools are installed
  ansible.builtin.apt:
    name:
      - curl
      - build-essential
    state: present
  tags: nodejs

- name: Add NodeSource 22.x repository and install Node.js
  ansible.builtin.shell: |
    curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
    apt-get install -y nodejs
  args:
    executable: /bin/bash
  tags: nodejs

- name: Verify Node.js installation
  ansible.builtin.command: node -v
  register: node_version
  changed_when: false

- name: Display installed Node.js version
  ansible.builtin.debug:
    msg: "Node.js version installed: {{ node_version.stdout }}"
