- name: Install PM2 globally
  npm:
    name: pm2
    global: yes

- name: Configure PM2 startup for app user
  become: yes
  shell: |
    env PATH=$PATH:/usr/bin pm2 startup systemd -u {{ app_user }} --hp /home/{{ app_user }}
  args:
    executable: /bin/bash

- name: Start Node JS app with PM2
  become: false
  shell: |
    pm2 start npm --name " {{ app_name }} " -- start
  args:
    chdir: "{{ deploy_dir }}"
    executable: /bin/bash

- name: Save PM2 process list
  become: yes
  shell: pm2 save
