---
# roles/node_server/tasks/3_pm2.yml
# Tasks to setup PM2 and start Node.js app

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes

- name: Configure PM2 startup for app user
  shell: |
    env PATH=$PATH:/usr/bin pm2 startup systemd -u {{ app_user }} --hp /home/{{ app_user }}
  args:
    executable: /bin/bash
  become: true

- name: Stop rogue Node.js processes running as root
  shell: pkill -u ubuntu node || true
  become: true
  ignore_errors: true

- name: Start Node.js app with PM2 (idempotent)
  become: true
  become_user: "{{ app_user }}"
  shell: |
    pm2 describe "{{ app_name }}" || pm2 start "{{ node_entry_point }}" --name "{{ app_name }}"
  args:
    chdir: "{{ deploy_dir }}"
    executable: /bin/bash

- name: Save PM2 process list
  become: true
  become_user: "{{ app_user }}"
  shell: pm2 save

- name: Reload app with PM2 if already running
  become: true
  become_user: "{{ app_user }}"
  shell: |
    pm2 reload "{{ app_name }}" || pm2 start "{{ node_entry_point }}" --name "{{ app_name }}"
  args:
    chdir: "{{ deploy_dir }}"
    executable: /bin/bash
  when: app_reload | default(false)

- name: Check PM2 process status
  become: true
  become_user: "{{ app_user }}"
  shell: pm2 list
  register: pm2_status

- name: Show PM2 status output
  debug:
    var: pm2_status.stdout
