# SPDX-License-Identifier: MIT-0
---
# tasks file for node_server

# 1️⃣ Install Node.js {{ nodejs_version }}, npm, git, and curl

- name: Ensure curl and git installed
  apt:
    name:
      - git
      - curl
    state: present
    update_cache: yes    
# 2️⃣ Ensure Deployment directory exists
- name: Ensure deployment directory exists
  file:
    path: "{{ deploy_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'


# 3️⃣ Clone or update Node.js application source code
- name: Clone or update Node.js application source code
  git:
    repo: "{{ github_nodejs_repo_url }}"
    dest: "{{ deploy_dir }}"
    version: "{{ git_branch_node }}"
    force: yes
    update: yes
    accept_hostkey: yes
  environment:
        GIT_ASKPASS: /tmp/git_askpass.sh
        GIT_TERMINAL_PROMPT: "0"
  become: yes  
  # become_user: "{{ app_user }}"

- name: Remove temporary askpass script
  file:
    path: /tmp/git_askpass.sh
    state: absent

# 4️⃣ Install Node.js dependencies
- name: Install Node.js dependencies
  npm:
    path: "{{ deploy_dir }}"
    production: yes
  become_user: "{{ app_user }}"


# 5️⃣ Copy environment variable file
- name: Configure environment variable file
  template:
    src: env.j2
    dest: "{{ deploy_dir }}/.env"
    owner: "{{ app_user }}"
    mode: '0644'
  notify: Restart Node App


# 6️⃣ Install PM2 globally
- name: Ensure Pre-requisites are installed
  import_tasks: 3_pm2.yml


# 8️⃣ Save PM2 process list
- name: Save PM2 process list
  become_user: "{{ app_user }}"
  command: pm2 save


# # 9️⃣ Setup PM2 startup service
# - name: Setup PM2 startup service
#   become_user: "{{ app_user }}"
#   command: pm2 startup systemd -u {{ app_user }} --hp /home/{{ app_user }}
