---
# 1️⃣ Change root authentication to password
- name: Change MySQL root auth to use mysql_native_password
  command: >
    mysql -u root --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
  args:
    creates: /root/.mysql_native_auth_done
  register: change_auth
  changed_when: change_auth.rc == 0

- name: Mark auth change as done
  file:
    path: /root/.mysql_native_auth_done
    state: touch

# 2️⃣ Remove anonymous users
- name: Remove anonymous MySQL users
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

# 3️⃣ Remove test database
- name: Remove MySQL test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
