---
# Install packages required for building a React app and add NodeSource repo.
- name: Ensure that the cache is up-to-date
  ansible.builtin.apt:
    update_cache: yes
  # when: ansible_os_family == "Debian"
  tags: nodejs

- name: Ensure curl is installed (Debian)
  ansible.builtin.apt:
    name: curl
    state: present
  # when: ansible_os_family == "Debian"
  tags: nodejs

- name: Add NodeSource repository GPG key
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
  # when: ansible_os_family == "Debian"
  tags: nodejs

- name: Add NodeSource repository
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    state: present
    filename: nodesource
  # when: ansible_os_family == "Debian"
  tags: nodejs

- name: Install Node.js and build-essential
  ansible.builtin.apt:
    name:
    - nodejs
    - build-essential
    state: present
    update_cache: yes
  # when: ansible_os_family == "Debian"

- name: Ensure xvfb is installed
  ansible.builtin.apt:
    name: xvfb
    state: present
    update_cache: yes

- name: Ensure Vite is installed locally
  command: sudo apt-get install vite -y
