---
- name: Restart Node App
  become: yes
  shell: |
    pm2 restart all || pm2 start npm --name "{{ app_name }}" -- start
  args:
    chdir: "{{ deploy_dir }}"
    executable: /bin/bash

- name: Restart Node App via PM2
  command: pm2 restart all
  become_user: "{{ app_user }}"
  ignore_errors: yes

- name: Save PM2 process list
  command: pm2 save
  become_user: "{{ app_user }}"
